name: SonarQube Code Analysis

on:
  workflow_dispatch:

jobs:
  sonar-analysis:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan - Frontend
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FE }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=chat-fe
            -Dsonar.projectName=chat-fe

      - name: SonarQube Scan - Backend
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BE }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=chat-be
            -Dsonar.projectName=chat-be
